import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Web3Provider } from "@/providers/Web3Provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased flex`}>
        <Web3Provider>
          <SidebarProvider>
            <Navigation />
            <main className="w-full">{children}</main>
          </SidebarProvider>
        </Web3Provider>
      </body>
    </html>
  );
}
