name: cardosis

services:
  cardosis-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: cardosis-backend
    container_name: cardosis-backend
    ports:
      - 6789:8000
    volumes:
      - app_data:/app/data
    env_file:
      - ../.env
    environment:
      - DOCKER_ENV=true
    networks:
      - cardosis

networks:
  cardosis:
    name: cardosis
    driver: bridge

volumes:
  app_data: